// =============================================================
// Sector Definitions — 24 sectors with module mapping
// =============================================================

export interface SectorConfig {
  key: string;
  name: string;
  nameAr: string;
  category: string;
  scales: string[];
  coreModules: string[];
  optionalModules: string[];
  aiCapabilities: string[];
  defaultCoaTemplate: string;
  defaultCostMethod: "avco" | "fifo" | "lifo";
}

export const SECTORS: Record<string, SectorConfig> = {
  grocery: {
    key: "grocery",
    name: "Grocery / Mini-market",
    nameAr: "بقالة / ميني ماركت",
    category: "retail",
    scales: ["micro", "small", "medium"],
    coreModules: ["accounting", "pos", "inventory", "sales"],
    optionalModules: ["crm", "marketing"],
    aiCapabilities: ["smart_reorder", "demand_forecast", "fraud_detection"],
    defaultCoaTemplate: "retail_standard",
    defaultCostMethod: "avco",
  },
  gas_station: {
    key: "gas_station",
    name: "Gas Station",
    nameAr: "محطة وقود",
    category: "retail",
    scales: ["micro", "small"],
    coreModules: ["accounting", "pos", "inventory", "sales"],
    optionalModules: ["fleet", "crm"],
    aiCapabilities: ["fuel_level_alerts", "shift_analytics", "fraud_detection"],
    defaultCoaTemplate: "retail_standard",
    defaultCostMethod: "avco",
  },
  shopping_mall: {
    key: "shopping_mall",
    name: "Shopping Mall",
    nameAr: "مجمع تجاري",
    category: "retail",
    scales: ["medium", "large", "enterprise"],
    coreModules: ["accounting", "facilities", "crm", "hr"],
    optionalModules: ["marketing", "legal"],
    aiCapabilities: ["tenant_analytics", "foot_traffic_prediction"],
    defaultCoaTemplate: "real_estate",
    defaultCostMethod: "avco",
  },
  auto_dealership: {
    key: "auto_dealership",
    name: "Auto Dealership",
    nameAr: "وكالة سيارات",
    category: "retail",
    scales: ["small", "medium", "large"],
    coreModules: ["accounting", "sales", "inventory", "crm"],
    optionalModules: ["fleet", "quality"],
    aiCapabilities: ["price_optimization", "service_reminders"],
    defaultCoaTemplate: "retail_standard",
    defaultCostMethod: "fifo",
  },
  pharmacy: {
    key: "pharmacy",
    name: "Pharmacy",
    nameAr: "صيدلية",
    category: "retail",
    scales: ["micro", "small", "medium"],
    coreModules: ["accounting", "pos", "inventory", "sales"],
    optionalModules: ["procurement", "quality"],
    aiCapabilities: ["expiry_alerts", "auto_reorder", "fraud_detection"],
    defaultCoaTemplate: "retail_standard",
    defaultCostMethod: "fifo",
  },
  restaurant: {
    key: "restaurant",
    name: "Restaurant / Cafe",
    nameAr: "مطعم / كافيه",
    category: "food_hospitality",
    scales: ["micro", "small", "medium"],
    coreModules: ["accounting", "pos", "inventory", "hr"],
    optionalModules: ["crm", "marketing"],
    aiCapabilities: ["menu_optimization", "waste_prediction", "demand_forecast"],
    defaultCoaTemplate: "food_service",
    defaultCostMethod: "avco",
  },
  hotel: {
    key: "hotel",
    name: "Hotel / Resort",
    nameAr: "فندق / منتجع",
    category: "food_hospitality",
    scales: ["small", "medium", "large", "enterprise"],
    coreModules: ["accounting", "sales", "hr", "facilities"],
    optionalModules: ["crm", "marketing", "procurement"],
    aiCapabilities: ["dynamic_pricing", "occupancy_forecast"],
    defaultCoaTemplate: "hospitality",
    defaultCostMethod: "avco",
  },
  bakery: {
    key: "bakery",
    name: "Bakery / Sweets",
    nameAr: "مخبز / حلويات",
    category: "food_hospitality",
    scales: ["micro", "small", "medium"],
    coreModules: ["accounting", "pos", "inventory", "manufacturing"],
    optionalModules: ["sales", "quality"],
    aiCapabilities: ["batch_planning", "demand_forecast"],
    defaultCoaTemplate: "manufacturing_standard",
    defaultCostMethod: "avco",
  },
  factory: {
    key: "factory",
    name: "Factory (Any Type)",
    nameAr: "مصنع",
    category: "manufacturing",
    scales: ["medium", "large", "enterprise"],
    coreModules: ["accounting", "inventory", "procurement", "manufacturing", "quality", "hr"],
    optionalModules: ["fleet", "supply_chain", "rnd"],
    aiCapabilities: ["production_scheduling", "predictive_maintenance", "defect_detection"],
    defaultCoaTemplate: "manufacturing_standard",
    defaultCostMethod: "avco",
  },
  construction: {
    key: "construction",
    name: "Construction",
    nameAr: "مقاولات",
    category: "manufacturing",
    scales: ["small", "medium", "large", "enterprise"],
    coreModules: ["accounting", "project_mgmt", "procurement", "hr"],
    optionalModules: ["fleet", "facilities", "legal"],
    aiCapabilities: ["cost_estimation", "schedule_optimization"],
    defaultCoaTemplate: "construction",
    defaultCostMethod: "avco",
  },
  mining: {
    key: "mining",
    name: "Mining / Extraction",
    nameAr: "تعدين / استخراج",
    category: "manufacturing",
    scales: ["large", "enterprise"],
    coreModules: ["accounting", "hr", "procurement", "hse", "fleet"],
    optionalModules: ["supply_chain", "facilities"],
    aiCapabilities: ["safety_prediction", "resource_optimization"],
    defaultCoaTemplate: "mining_energy",
    defaultCostMethod: "avco",
  },
  consulting: {
    key: "consulting",
    name: "Consulting / Professional",
    nameAr: "استشارات",
    category: "services",
    scales: ["micro", "small", "medium", "large"],
    coreModules: ["accounting", "project_mgmt", "hr", "crm"],
    optionalModules: ["document_mgmt", "marketing"],
    aiCapabilities: ["time_tracking", "client_insights"],
    defaultCoaTemplate: "services_standard",
    defaultCostMethod: "avco",
  },
  salon: {
    key: "salon",
    name: "Beauty Salon / Spa",
    nameAr: "صالون تجميل",
    category: "services",
    scales: ["micro", "small"],
    coreModules: ["accounting", "pos", "hr"],
    optionalModules: ["crm", "marketing"],
    aiCapabilities: ["booking_optimization", "client_preferences"],
    defaultCoaTemplate: "services_standard",
    defaultCostMethod: "avco",
  },
  laundry: {
    key: "laundry",
    name: "Laundry / Dry Cleaning",
    nameAr: "مغسلة",
    category: "services",
    scales: ["micro", "small", "medium"],
    coreModules: ["accounting", "pos", "inventory"],
    optionalModules: ["fleet", "crm"],
    aiCapabilities: ["route_optimization", "demand_prediction"],
    defaultCoaTemplate: "services_standard",
    defaultCostMethod: "avco",
  },
  auto_repair: {
    key: "auto_repair",
    name: "Auto Repair Workshop",
    nameAr: "ورشة سيارات",
    category: "services",
    scales: ["micro", "small", "medium"],
    coreModules: ["accounting", "pos", "inventory"],
    optionalModules: ["crm", "fleet"],
    aiCapabilities: ["parts_forecasting", "service_history_ai"],
    defaultCoaTemplate: "services_standard",
    defaultCostMethod: "avco",
  },
  clinic: {
    key: "clinic",
    name: "Clinic / Hospital",
    nameAr: "عيادة / مستشفى",
    category: "healthcare_education",
    scales: ["small", "medium", "large", "enterprise"],
    coreModules: ["accounting", "hr", "procurement", "crm"],
    optionalModules: ["facilities", "legal", "quality"],
    aiCapabilities: ["appointment_optimization", "inventory_alerts"],
    defaultCoaTemplate: "healthcare",
    defaultCostMethod: "avco",
  },
  school: {
    key: "school",
    name: "School / University",
    nameAr: "مدرسة / جامعة",
    category: "healthcare_education",
    scales: ["small", "medium", "large", "enterprise"],
    coreModules: ["accounting", "hr", "facilities"],
    optionalModules: ["crm", "document_mgmt", "project_mgmt"],
    aiCapabilities: ["smart_training", "performance_evaluation"],
    defaultCoaTemplate: "education",
    defaultCostMethod: "avco",
  },
  training_center: {
    key: "training_center",
    name: "Training Center",
    nameAr: "مركز تدريب",
    category: "healthcare_education",
    scales: ["micro", "small", "medium"],
    coreModules: ["accounting", "hr", "crm"],
    optionalModules: ["marketing", "document_mgmt"],
    aiCapabilities: ["adaptive_curriculum", "learner_analytics"],
    defaultCoaTemplate: "education",
    defaultCostMethod: "avco",
  },
  bank: {
    key: "bank",
    name: "Bank / Financial",
    nameAr: "بنك / مؤسسة مالية",
    category: "finance_government",
    scales: ["medium", "large", "enterprise"],
    coreModules: ["accounting", "treasury", "hr", "legal", "audit"],
    optionalModules: ["crm", "it_desk", "facilities"],
    aiCapabilities: ["fraud_detection", "risk_scoring", "aml"],
    defaultCoaTemplate: "banking",
    defaultCostMethod: "avco",
  },
  insurance: {
    key: "insurance",
    name: "Insurance",
    nameAr: "تأمين",
    category: "finance_government",
    scales: ["medium", "large", "enterprise"],
    coreModules: ["accounting", "crm", "hr", "legal"],
    optionalModules: ["marketing", "document_mgmt"],
    aiCapabilities: ["claims_prediction", "underwriting_ai"],
    defaultCoaTemplate: "insurance",
    defaultCostMethod: "avco",
  },
  government: {
    key: "government",
    name: "Government Entity",
    nameAr: "جهة حكومية",
    category: "finance_government",
    scales: ["large", "enterprise"],
    coreModules: ["accounting", "hr", "procurement", "legal", "facilities"],
    optionalModules: ["project_mgmt", "document_mgmt", "it_desk"],
    aiCapabilities: ["budget_optimization", "service_delivery_analytics"],
    defaultCoaTemplate: "government",
    defaultCostMethod: "avco",
  },
  ngo: {
    key: "ngo",
    name: "NGO / Non-Profit",
    nameAr: "منظمة غير ربحية",
    category: "finance_government",
    scales: ["micro", "small", "medium", "large"],
    coreModules: ["accounting", "hr", "project_mgmt"],
    optionalModules: ["crm", "marketing", "document_mgmt"],
    aiCapabilities: ["donor_analytics", "impact_measurement"],
    defaultCoaTemplate: "ngo",
    defaultCostMethod: "avco",
  },
  ecommerce: {
    key: "ecommerce",
    name: "E-Commerce",
    nameAr: "تجارة إلكترونية",
    category: "retail",
    scales: ["micro", "small", "medium", "large"],
    coreModules: ["accounting", "inventory", "sales", "crm"],
    optionalModules: ["marketing", "supply_chain"],
    aiCapabilities: ["demand_forecast", "dynamic_pricing", "churn_prediction"],
    defaultCoaTemplate: "retail_standard",
    defaultCostMethod: "avco",
  },
  logistics: {
    key: "logistics",
    name: "Logistics / Transport",
    nameAr: "نقل / لوجستيك",
    category: "services",
    scales: ["small", "medium", "large", "enterprise"],
    coreModules: ["accounting", "fleet", "hr", "procurement"],
    optionalModules: ["crm", "facilities"],
    aiCapabilities: ["route_optimization", "predictive_maintenance", "fuel_analytics"],
    defaultCoaTemplate: "logistics",
    defaultCostMethod: "avco",
  },
};

export const SECTOR_CATEGORIES = {
  retail: { name: "Retail & Trade", nameAr: "تجزئة وتجارة" },
  food_hospitality: { name: "Food & Hospitality", nameAr: "طعام وضيافة" },
  manufacturing: { name: "Manufacturing & Industry", nameAr: "صناعة" },
  services: { name: "Services", nameAr: "خدمات" },
  healthcare_education: { name: "Healthcare & Education", nameAr: "صحة وتعليم" },
  finance_government: { name: "Finance & Government", nameAr: "مالية وحكومة" },
};

export const SCALE_LEVELS = {
  micro: { name: "Micro", nameAr: "متناهية الصغر", minEmployees: 1, maxEmployees: 5 },
  small: { name: "Small", nameAr: "صغيرة", minEmployees: 6, maxEmployees: 25 },
  medium: { name: "Medium", nameAr: "متوسطة", minEmployees: 26, maxEmployees: 200 },
  large: { name: "Large", nameAr: "كبيرة", minEmployees: 201, maxEmployees: 1000 },
  enterprise: { name: "Enterprise", nameAr: "مؤسسات", minEmployees: 1001, maxEmployees: 999999 },
};
